// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pgnvmftahiahjdxdlciv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBnbnZtZnRhaGlhaGpkeGRsY2l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2NDA2NDIsImV4cCI6MjA2OTIxNjY0Mn0.-kl74fQ4My2CdJoFjjFtD9ziCr0BOk2i8_tXbnW-nCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});